//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HarveyJobs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbScheduledJob
    {
        public int JobsID { get; set; }
        public int AppID { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string Day { get; set; }
        public string Success { get; set; }
        public Nullable<int> Files_DwUp { get; set; }
        public Nullable<int> Files_Sorted { get; set; }
    
        public virtual tbAppInfo tbAppInfo { get; set; }
    }
}
